### PR TITLE
Package for pypi

### PR DESCRIPTION
**Pull request by alistair-broomhead**
The following makes pip bash autocompletion installable via setuptools whether from a distributable package, of via python setup.py install.

Up for discussion:
 - What should happen at install time? Currently I call the install() function then the update() function, but we could leave more to be done by the user.
 - Should we be appending ~/.bashrc, ~/.profile, none of the above?
 - Once this is packaged should it be an install dependancy of pip-extras, or an extras package?

### CODE REVIEW

**Comment by alistair-broomhead** [comment]
this goes with #1

**Comment by alistair-broomhead** [comment]
WRT the second bullet point, I've been testing this under windows with both git bash and cygwin - without appending one of these profiles there is no completion - if we don't do this for people we should probably note somewhere that `. ~/.bash_completion.d/pip` is required for this to have any effect.

**Comment by alistair-broomhead** [comment]
@russel this pull request and its related issue have been inactive without comment for some time, and are the only thing standing in the way of producing a package for pypi.

I'm happy to wait, but if you don't have time to maintain the project could you please add me as a contributor so I can push this through myself? I'd base the package off my own fork, but seeing as most of the hard work was done by yourself and @papaloizouc it would feel somewhat disingenuous for it not to be hosted from one of your Github accounts.

**Comment by russel** [comment]
I pressed the merge button too early. I am not convinced this is the right way forward. Bash completion scripts should be self-standing things people can download and install. I appreciate that this is a Python specific one. Should we be in the Python pip arena for this or the Bash completion arena?

**Comment by russel** [comment]
Despite the mess, I have reverted, but now we have the Python oriented material in the repository so we can go in whatever direction we want just by manipulations with Git.

**Comment by russel** [comment]
Sorry for creating the mess, bad review approach on my part.

**Comment by alistair-broomhead** [comment]
@russel I can see what you're saying, but I think the waters are muddied somewhat.

From my point of view this repository marks the first step towards providing an apt-get inspired option where many pip operations work off a local cache rather than making repeated requests to the package index, and so I would like to have cache-building be something we can pull in as a python package dependency (we could store far more info that we currently are within our cache, such as version numbers and dependency graphs). 

This is however then also a dependency for the bash autocompletion script, which as you rightly note, is something you might expect to be installed manually. Having this be a dependency for the autocompletion script is however somewhat messy.My suggestion therefore is that maybe we make this a python package, but do not install the autocompletion script. We could add an extra command that will install the autocompletion script, but not have it run on install.

As far as I can see this would solve the dependency issue and not violate the principle of least surprise by having bash autocompletion added without being explicitly required, but there is probably something somewhere that I have no considered. My main concern is in trying to get this into some form of easily deployed state within a reasonable timeframe so I can tell others who have been asking how to get hold of it.

**Comment by alistair-broomhead** [comment]
@russel , @papaloizouc what are your thoughts on how to proceed? I don't want to bulldoze through, it's just that I have time on my hands ATM ;)

**Comment by russel** [comment]
It strikes me there are actually two projects here. One is the original Bash completion script, and I think that should remain free standing in standard Bash completion script tradition, exactly because there is a culture already behind these things. The second project stems from the need of the bash completion script to have a cache, and is actually an extension to pip. Clearly there is a coupling and hence dependency, which is going to be a bit awkward to handle. Nonetheless I wonder if it might be best to keep them separate initially. Perhaps take the code you had that is now in here (ish), and create a repository pip_cache. This can be dedicated to making a PyPI package since it has no Bash relationship per se. Then we can use co-working between the two repositories (things like the cache creation script) until we can find a way of sensibly organizing things. This gives us ability to move forward and yet delay some decisions.

**Comment by papaloizouc** [comment]
something random, i was wandering if both repositories could be built-in in pip so you don't have to look for them

**Comment by alistair-broomhead** [comment]
Ok, so pip-cache would be a dependency of any pip-extras package that uses it, one of which would be pip-bashcompletion, but maybe pip-extras has an optional extras dependency of pip-bashcompletion?

This way bash auto completion is kept separate, and won't be installed automatically by pip, but can be added with pip, and will at least be suggested, which would aid discovery.

**Pull request merged**
